# Matrizes
Tabela de elementos dispostos em linhas e colunas.

\begin{equation}
A_{m \times n} =
  \begin{bmatrix}
    a_{1 1} & a_{1 2} & \cdots & a_{1 n} \\
    a_{2 1} & a_{2 2} & \cdots & a_{2 n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m 1} & a_{m 2} & \cdots & a_{m n}
  \end{bmatrix} = [a_{ij}]_{m \times n}
\end{equation}

**Declaração de matrizes no Numpy**:

In [1]:
import numpy as np

In [2]:
A = np.array([
    [2,-1],
    [0,4]
])

B = np.matrix('2 -1; 0 4')

C = np.matrix([
    [2,-1],
    [0,4]
])

In [3]:
print(A, type(A), A.shape)
print(B, type(B), B.shape)
print(C, type(C), C.shape)

[[ 2 -1]
 [ 0  4]] <class 'numpy.ndarray'> (2, 2)
[[ 2 -1]
 [ 0  4]] <class 'numpy.matrix'> (2, 2)
[[ 2 -1]
 [ 0  4]] <class 'numpy.matrix'> (2, 2)


## Tipos de matrizes
Alguns tipos de matrizes que são importantes de saber.

### Quadrada
O número de linhas é igual ao número de colunas ($m=n$).

\begin{equation}
A_{1 \times 1} =
  \begin{bmatrix}
    a_{1 1}
  \end{bmatrix}
\\
B_{2 \times 2} =
  \begin{bmatrix}
    a_{1 1} & a_{1 2} \\
    a_{2 1} & a_{2 2}
  \end{bmatrix}
\\
C_{3 \times 3} =
  \begin{bmatrix}
    a_{1 1} & a_{1 2} & a_{1 3} \\
    a_{2 1} & a_{2 2} & a_{2 3} \\
    a_{3 1} & a_{3 2} & a_{3 3}
  \end{bmatrix}
\end{equation}

In [4]:
Q1 = np.empty((1,1))
Q2 = np.empty((2,2))
Q3 = np.empty((3,3))

print(Q1, type(Q1), Q1.shape)
print(Q2, type(Q2), Q2.shape)
print(Q3, type(Q3), Q3.shape)

[[nan]] <class 'numpy.ndarray'> (1, 1)
[[4.68953893e-310 4.68953892e-310]
 [0.00000000e+000 0.00000000e+000]] <class 'numpy.ndarray'> (2, 2)
[[6.93961144e-310 4.68953920e-310 9.00687745e-313]
 [1.45259949e-308 1.87160735e-311 3.00384344e-273]
 [2.07224410e+243 2.54018677e+151 8.88782411e+252]] <class 'numpy.ndarray'> (3, 3)


### Nula
$a_{i j} = 0$, para todo $i$ e $j$.

\begin{equation}
A_{2 \times 2} =
  \begin{bmatrix}
    0 & 0 \\
    0 & 0
  \end{bmatrix}
\\
B_{3 \times 5} =
  \begin{bmatrix}
    0 & 0 & 0 & 0 & 0 \\
    0 & 0 & 0 & 0 & 0 \\
    0 & 0 & 0 & 0 & 0
  \end{bmatrix}
\end{equation}

In [5]:
N1 = np.zeros((2,2))
N2 = np.zeros([3,5])

print(N1, type(N1), N1.shape)
print(N2, type(N2), N2.shape)

[[0. 0.]
 [0. 0.]] <class 'numpy.ndarray'> (2, 2)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] <class 'numpy.ndarray'> (3, 5)


### Matriz-coluna
Possui apenas uma coluna ($n=1$).

\begin{equation}
A_{m \times 1} =
  \begin{bmatrix}
    a_{1 1} \\
    a_{2 1} \\
    \vdots \\
    a_{m 1} \\
  \end{bmatrix}
\end{equation}

In [6]:
C = np.array([[1], [3], [5]])

print(C, type(C), C.shape)

[[1]
 [3]
 [5]] <class 'numpy.ndarray'> (3, 1)


### Matriz-linha
Possui apenas uma linha ($m=1$).

\begin{equation}
A_{1 \times n} =
  \begin{bmatrix}
    a_{1 1} & a_{1 2} & \cdots & a_{1 n}
  \end{bmatrix}
\end{equation}

In [7]:
L = np.array([[2, 4, 6]])

print(L, type(L), L.shape)

[[2 4 6]] <class 'numpy.ndarray'> (1, 3)


### Diagonal
- $m = n$, ou seja, é uma matriz quadrada;
- $a_{i j} = 0$, para todo $i \neq j$;
- $a_{i j}$ assume um valor diferente de $0$, para todo $i = j$.

\begin{equation}
A_{3 \times 3} =
  \begin{bmatrix}
    7 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & -1
  \end{bmatrix}
\\
B_{4 \times 4} =
  \begin{bmatrix}
    3 & 0 & 0 & 0 \\
    0 & 3 & 0 & 0 \\
    0 & 0 & 3 & 0 \\
    0 & 0 & 0 & 3
  \end{bmatrix}
\end{equation}

In [8]:
D1 = np.diag([7, 1, -1])
D2 = np.diag([3, 3, 3, 3])

print(D1, type(D1), D1.shape)
print(D2, type(D2), D2.shape)

[[ 7  0  0]
 [ 0  1  0]
 [ 0  0 -1]] <class 'numpy.ndarray'> (3, 3)
[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]] <class 'numpy.ndarray'> (4, 4)


### Identidade quadrada
- $m = n$, ou seja, é uma matriz quadrada;
- $a_{i j} = 1$, para todo $i = j$;
- $a_{i j} = 0$, para todo $i \neq j$.

\begin{equation}
A_{m \times n} =
  \begin{bmatrix}
    1 & 0 & \cdots & 0 \\
    0 & 1 & \cdots & 0 \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \cdots & 1
  \end{bmatrix}
\end{equation}

In [9]:
I1 = np.eye(4)
I2 = np.identity(4, int)

print(I1, type(I1), I1.shape)
print(I2, type(I2), I2.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] <class 'numpy.ndarray'> (4, 4)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'> (4, 4)


### Matriz triangular inferior
- $m = n$, ou seja, é uma matriz quadrada;
- $a_{i j} = 0$, para todo $i < j$.

\begin{equation}
A_{m \times n} =
  \begin{bmatrix}
    a_{1 1} & 0 & 0 & \cdots & 0 \\
    a_{2 1} & a_{2 2} & 0 & \cdots & 0 \\
    a_{3 1} & a_{3 2} & a_{3 3} & \cdots & 0 \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    a_{m 1} & a_{m 2} & a_{m 3} & \cdots & a_{m n}
  \end{bmatrix}
\end{equation}

In [10]:
Ti1 = np.tril([[1,2,3],[4,5,6],[7,8,9]])
Ti2 = np.tril([[1,2,3],[4,5,6],[7,8,9]], -1)
Ti3 = np.tril([[1,2,3],[4,5,6],[7,8,9]], -2)
Ti4 = np.tril([[1,2,3],[4,5,6],[7,8,9]], 1)

print(Ti1, type(Ti1), Ti1.shape)
print(Ti2, type(Ti2), Ti2.shape)
print(Ti3, type(Ti3), Ti3.shape)
print(Ti4, type(Ti4), Ti4.shape)

[[1 0 0]
 [4 5 0]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)
[[0 0 0]
 [4 0 0]
 [7 8 0]] <class 'numpy.ndarray'> (3, 3)
[[0 0 0]
 [0 0 0]
 [7 0 0]] <class 'numpy.ndarray'> (3, 3)
[[1 2 0]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


### Matriz triangular superior
- $m = n$, ou seja, é uma matriz quadrada;
- $a_{i j} = 0$, para todo $i > j$.

\begin{equation}
A_{m \times n} =
  \begin{bmatrix}
    a_{1 1} & a_{1 2} & a_{1 3} & \cdots & a_{1 n} \\
    0 & a_{2 2} & a_{2 3} & \cdots & a_{2 n} \\
    0 & 0 & a_{3 3} & \cdots & a_{3 n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & 0 & \cdots & a_{m n}
  \end{bmatrix}
\end{equation}

In [11]:
Ts1 = np.triu([[1,2,3],[4,5,6],[7,8,9]])
Ts2 = np.triu([[1,2,3],[4,5,6],[7,8,9]], 1)
Ts3 = np.triu([[1,2,3],[4,5,6],[7,8,9]], 2)
Ts4 = np.triu([[1,2,3],[4,5,6],[7,8,9]], -1)

print(Ts1, type(Ts1), Ts1.shape)
print(Ts2, type(Ts2), Ts2.shape)
print(Ts3, type(Ts3), Ts3.shape)
print(Ts4, type(Ts4), Ts4.shape)

[[1 2 3]
 [0 5 6]
 [0 0 9]] <class 'numpy.ndarray'> (3, 3)
[[0 2 3]
 [0 0 6]
 [0 0 0]] <class 'numpy.ndarray'> (3, 3)
[[0 0 3]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'> (3, 3)
[[1 2 3]
 [4 5 6]
 [0 8 9]] <class 'numpy.ndarray'> (3, 3)


### Matriz simétrica
- $m = n$, ou seja, é uma matriz quadrada;
- $a_{i j} = a_{j i}$.

\begin{equation}
A_{4 \times 4} =
  \begin{bmatrix}
    a & b & c & d \\
    b & e & f & g \\
    c & f & h & i \\
    d & g & i & k
  \end{bmatrix}
\end{equation}

In [12]:
S1 = np.tril([[1,2,3],[4,5,6],[7,8,9]], -1)
S1 = S1 + S1.T

print(S1, type(S1), S1.shape)

[[0 4 7]
 [4 0 8]
 [7 8 0]] <class 'numpy.ndarray'> (3, 3)


### Matriz transposta
É a matriz que se obtém da troca de linhas por colunas de uma dada matriz.

\begin{equation}
A_{2 \times 3} =
  \begin{bmatrix}
    a_{1 1} & a_{1 2} & a_{1 3} \\
    a_{2 1} & a_{2 2} & a_{2 3}
  \end{bmatrix}
\\
A_{3 \times 2}^{t} =
  \begin{bmatrix}
    a_{1 1} & a_{2 1} \\
    a_{1 2} & a_{2 2} \\
    a_{1 3} & a_{2 3}
  \end{bmatrix}
\end{equation}

In [13]:
A = np.matrix('2 1; 0 3; -1 4')
AT = A.T  # np.transpose(A)

print(A, type(A), A.shape)
print(AT, type(AT), AT.shape)

[[ 2  1]
 [ 0  3]
 [-1  4]] <class 'numpy.matrix'> (3, 2)
[[ 2  0 -1]
 [ 1  3  4]] <class 'numpy.matrix'> (2, 3)


## Operações com matrizes
Algumas operações que envolvem matrizes.

In [14]:
A = np.array([[2,4,6], [1,2,7], [3,2,9]])
B = np.array([[-1,4,5], [6,3,1]])
C = np.array([[0,4,3], [1,-3,-1], [3,1,2]])

In [15]:
print(A, type(A), A.shape)
print(B, type(B), B.shape)
print(C, type(C), C.shape)

[[2 4 6]
 [1 2 7]
 [3 2 9]] <class 'numpy.ndarray'> (3, 3)
[[-1  4  5]
 [ 6  3  1]] <class 'numpy.ndarray'> (2, 3)
[[ 0  4  3]
 [ 1 -3 -1]
 [ 3  1  2]] <class 'numpy.ndarray'> (3, 3)


### Multiplicação por um escalar
$k \cdot A = [ka_{i j}]_{m \times n}$.

\begin{equation}
k \cdot
  \begin{bmatrix}
    a & b & c \\
    d & e & f
  \end{bmatrix} =
  \begin{bmatrix}
    ka & kb & kc \\
    kd & ke & kf
  \end{bmatrix}
\end{equation}

In [16]:
B.dot(7)

array([[-7, 28, 35],
       [42, 21,  7]])

### Adição
As matrizes devem ter a mesma ordem.

\begin{equation}
  \begin{bmatrix}
    a & b \\
    c & d \\
    e & f
  \end{bmatrix} +
  \begin{bmatrix}
    g & h \\
    i & j \\
    k & l
  \end{bmatrix} =
  \begin{bmatrix}
    a+g & b+h \\
    c+i & d+j \\
    e+k & f+l
  \end{bmatrix}
\end{equation}

In [17]:
np.add(A, C)

array([[ 2,  8,  9],
       [ 2, -1,  6],
       [ 6,  3, 11]])

### Subtração
As matrizes devem ter a mesma ordem.

\begin{equation}
  \begin{bmatrix}
    a & b \\
    c & d \\
    e & f
  \end{bmatrix} -
  \begin{bmatrix}
    g & h \\
    i & j \\
    k & l
  \end{bmatrix} =
  \begin{bmatrix}
    a-g & b-h \\
    c-i & d-j \\
    e-k & f-l
  \end{bmatrix}
\end{equation}

In [18]:
np.subtract(A, C)

array([[2, 0, 3],
       [0, 5, 8],
       [0, 1, 7]])

### Multiplicação
Sejam $A = [a_{i j}]_{m \times n}$ e $B = [b_{r s}]_{n \times p}$. Definimos $A \cdot B = [c_{uv}]_{m \times p}$. O número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.

\begin{equation}
  \begin{bmatrix}
    a & b \\
    c & d \\
    e & f
  \end{bmatrix} \cdot
  \begin{bmatrix}
    g & h \\
    i & j
  \end{bmatrix} =
  \begin{bmatrix}
    (a \cdot g + b \cdot i) & (a \cdot h + b \cdot j) \\
    (c \cdot g + d \cdot i) & (c \cdot h + d \cdot j) \\
    (e \cdot g + f \cdot i) & (e \cdot h + f \cdot j)
  \end{bmatrix}
\end{equation}

In [19]:
np.dot(B, A)

array([[17, 14, 67],
       [18, 32, 66]])

## Cadeias de Markov
A transição de um estado para outro possui uma probabilidade.

- **Processo de Markov**: depende apenas do estado atual do fenômeno e estado seguinte.